services:
  app:
    image: syantrywave/todo-app:1.2.0
    env_file:
      - .env
    restart: always
#    environment:
#      - JAVA_OPTS='-XX:+UseSerialGC'
#      JAVA_OPTS:
#        -XX:+UseSerialGC
#        -Xss512k
#        -XX:MaxRAM=72m
#java -XX:+UseSerialGC -Xss512k -XX:MaxRAM=72m
    depends_on:
      - todo_db
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 300M
  todo_db:
    image: postgres
    env_file:
      - db.env
#    restart: always
    ports:
      - "5422:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
