services:
  app:
    image: syantrywave/todo-app:1.0.1
    restart: always
    depends_on:
      - todo_db
    ports:
      - "8080:8080"
  todo_db:
    image: postgres
    restart: always
    ports:
      - "5422:5432"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
